# Generated by Django 2.2.2 on 2019-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='materi_others',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
